export { Logo } from "./logo";
export { Main } from "./main";
export { Button } from "./button";
export { Card } from "./card";
export { Cards } from "./cards";
export { Footer } from "./footer";
export {OurReferences} from './ourReferences';
export {Header} from './header';
export {Basarilarimiz} from './basarilarimiz';
export {Hizmetler} from './boxes';
export {SloganArea} from './sloganArea/intex';
export {Blog} from './Blog';
export {Activities } from './activities';
